import { MigrationInterface, QueryRunner } from 'typeorm';

export class RestOfUserModuleTables1755363461338 implements MigrationInterface {
  name = 'RestOfUserModuleTables1755363461338';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(/*sql*/ `CREATE TABLE device_auth_session (
  id uuid NOT NULL,
  iat integer NOT NULL,
  expiration timestamp with time zone NOT NULL,
  ip character varying(39) NOT NULL,
  title text NOT NULL,
  "userId" uuid NOT NULL,
  CONSTRAINT "PK_6a02749fe2a1f7121df32d83514" PRIMARY KEY (id)
)`);
    await queryRunner.query(/*sql*/ `CREATE TABLE email_confirmation (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "confirmationCode" uuid,
  "expirationDate" timestamp with time zone,
  "isConfirmed" boolean NOT NULL,
  "userId" uuid NOT NULL,
  CONSTRAINT "UQ_43a950e0d84043eb32a4e0d6e22" UNIQUE ("confirmationCode"),
  CONSTRAINT "REL_28d3d3fbd7503f3428b94fd18c" UNIQUE ("userId"),
  CONSTRAINT "PK_ff2b80a46c3992a0046b07c5456" PRIMARY KEY (id)
)`);
    await queryRunner.query(/*sql*/ `CREATE TABLE password_recovery (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "confirmationCode" uuid NOT NULL,
  "expirationDate" timestamp with time zone NOT NULL,
  "userId" uuid,
  CONSTRAINT "UQ_496bfbe3ba7cd11c8ea1190dda3" UNIQUE ("confirmationCode"),
  CONSTRAINT "REL_f5b57d414cf38032bbbe9ec578" UNIQUE ("userId"),
  CONSTRAINT "PK_104b7650227e31deb0f4c9e7d4b" PRIMARY KEY (id)
)`);
    await queryRunner.query(/*sql*/ `ALTER TABLE device_auth_session ADD CONSTRAINT "FK_cfcefd8d3f68b515c31c82262f3" FOREIGN KEY (
  "userId"
) REFERENCES users (id) ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(/*sql*/ `ALTER TABLE email_confirmation ADD CONSTRAINT "FK_28d3d3fbd7503f3428b94fd18cc" FOREIGN KEY (
  "userId"
) REFERENCES users (id) ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(/*sql*/ `ALTER TABLE password_recovery ADD CONSTRAINT "FK_f5b57d414cf38032bbbe9ec578d" FOREIGN KEY (
  "userId"
) REFERENCES users (id) ON DELETE CASCADE ON UPDATE NO ACTION`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(/*sql*/ `ALTER TABLE password_recovery
DROP CONSTRAINT "FK_f5b57d414cf38032bbbe9ec578d"`);
    await queryRunner.query(/*sql*/ `ALTER TABLE email_confirmation
DROP CONSTRAINT "FK_28d3d3fbd7503f3428b94fd18cc"`);
    await queryRunner.query(/*sql*/ `ALTER TABLE device_auth_session
DROP CONSTRAINT "FK_cfcefd8d3f68b515c31c82262f3"`);
    await queryRunner.query(/*sql*/ `DROP TABLE password_recovery`);
    await queryRunner.query(/*sql*/ `DROP TABLE email_confirmation`);
    await queryRunner.query(/*sql*/ `DROP TABLE device_auth_session`);
  }
}
